d
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/auto-ci.yaml b/.github/workflows/auto-ci.yaml
--- a/.github/workflows/auto-ci.yaml
+++ b/.github/workflows/auto-ci.yaml
@@ -77,33 +77,47 @@ jobs:
         id: get_ref
         run: |
           if ${{ github.event_name == 'workflow_dispatch' }} ; then
-            echo "call by self workflow_dispatch"
-            echo "RUN_TAG=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
-            echo "RUN_E2E_LABEL=${{ github.event.inputs.e2e_labels }}" >> $GITHUB_ENV
-            echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
-            echo "RUN_UNITEST_ENABLED=true" >> $GITHUB_ENV
-            if ${{ github.event.inputs.ipfamily == 'ipv4' }}; then
-              echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
-              echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
-              echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
-            elif ${{ github.event.inputs.ipfamily == 'ipv6' }}; then
-              echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
-              echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
-              echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
-            elif ${{ github.event.inputs.ipfamily == 'dual' }}; then
-              echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
-              echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
-              echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
-            elif ${{ github.event.inputs.ipfamily == 'all' }}; then
-              echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
-              echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
-              echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
-            else
-              echo "error, unknown input ipfamily: ${{ github.event.inputs.ipfamily }} "
-              exit 1
-            fi
+              # github could not tell workflow_dispatch and workflow_call
+              if ${{ github.event.inputs.ipfamily == '' }} ; then
+                    # workflow_call event, nightly ci, run all e2e
+                    # use main sha for ci image tag
+                    echo "trigger by workflow_call"
+                    echo "RUN_TAG=main" >> $GITHUB_ENV
+                    echo "RUN_E2E_LABEL=" >> $GITHUB_ENV
+                    echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
+                    echo "RUN_UNITEST_ENABLED=true" >> $GITHUB_ENV
+                    echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
+                    echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
+                    echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
+              else
+                    echo "call by self workflow_dispatch"
+                    echo "RUN_TAG=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
+                    echo "RUN_E2E_LABEL=${{ github.event.inputs.e2e_labels }}" >> $GITHUB_ENV
+                    echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
+                    echo "RUN_UNITEST_ENABLED=true" >> $GITHUB_ENV
+                    if ${{ github.event.inputs.ipfamily == 'ipv4' }}; then
+                      echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
+                      echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
+                      echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
+                    elif ${{ github.event.inputs.ipfamily == 'ipv6' }}; then
+                      echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
+                      echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
+                      echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
+                    elif ${{ github.event.inputs.ipfamily == 'dual' }}; then
+                      echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
+                      echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
+                      echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
+                    elif ${{ github.event.inputs.ipfamily == 'all' }}; then
+                      echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
+                      echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
+                      echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
+                    else
+                      echo "error, unknown input ipfamily: ${{ github.event.inputs.ipfamily }} "
+                      exit 1
+                    fi
+              fi
           elif ${{ github.event_name == 'push' }} ; then
-            echo "trigger by push"
+              echo "trigger by push"
               echo "RUN_TAG=${{ github.sha }}" >> $GITHUB_ENV
               echo "RUN_E2E_LABEL=smoke" >> $GITHUB_ENV
               echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
@@ -113,35 +127,26 @@ jobs:
               echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
               echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
           elif ${{ github.event_name == 'pull_request_target' }} ; then
-            echo "trigger by pull_request_target"
-              echo "RUN_TAG=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
-            if ${{ steps.filter_pr.outputs.all_e2e == 'true' }} ; then
-                # run all e2e
-                echo "RUN_E2E_LABEL=" >> $GITHUB_ENV
-                echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
-                echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
-                echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
-            else
-                echo "RUN_E2E_LABEL=smoke" >> $GITHUB_ENV
-                echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
-                echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
-                echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
-            fi
-            echo "RUN_E2E_ENABLED=${{ steps.filter_pr.outputs.run_e2e }}" >> $GITHUB_ENV
-            # do it in another workflow
-            echo "RUN_UNITEST_ENABLED=false" >> $GITHUB_ENV
+              echo "trigger by pull_request_target"
+                echo "RUN_TAG=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
+              if ${{ steps.filter_pr.outputs.all_e2e == 'true' }} ; then
+                  # run all e2e
+                  echo "RUN_E2E_LABEL=" >> $GITHUB_ENV
+                  echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
+                  echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
+                  echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
+              else
+                  echo "RUN_E2E_LABEL=smoke" >> $GITHUB_ENV
+                  echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
+                  echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
+                  echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
+              fi
+              echo "RUN_E2E_ENABLED=${{ steps.filter_pr.outputs.run_e2e }}" >> $GITHUB_ENV
+              # do it in another workflow
+              echo "RUN_UNITEST_ENABLED=false" >> $GITHUB_ENV
           else
-            # workflow_call event
-            # use main sha for ci image tag
-            echo "trigger by workflow_call"
-              echo "RUN_TAG=main" >> $GITHUB_ENV
-            # nightly ci, run all e2e
-              echo "RUN_E2E_LABEL=" >> $GITHUB_ENV
-              echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
-              echo "RUN_UNITEST_ENABLED=true" >> $GITHUB_ENV
-              echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
-              echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
-              echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
+            echo "uknown event"
+            exit 1
           fi
 
       # some event, the tag is not sha, so checkout it and get sha
