sad
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/auto-ci.yaml b/.github/workflows/auto-ci.yaml
--- a/.github/workflows/auto-ci.yaml
+++ b/.github/workflows/auto-ci.yaml
@@ -2,7 +2,9 @@ name: Auto CI
 
 permissions: write-all
 on:
-  workflow_call:
+  schedule:
+    # each day
+    - cron: "0 20 * * *"
   pull_request_target:
     types:
       - opened
@@ -69,45 +71,31 @@ jobs:
         id: get_ref
         run: |
           if ${{ github.event_name == 'workflow_dispatch' }} ; then
-              # github could not tell workflow_dispatch and workflow_call
-              if ${{ github.event.inputs.ipfamily == '' }} ; then
-                    # workflow_call event, nightly ci, run all e2e
-                    # use main sha for ci image tag
-                    echo "trigger by workflow_call"
-                    echo "RUN_TAG=main" >> $GITHUB_ENV
-                    echo "RUN_E2E_LABEL=" >> $GITHUB_ENV
-                    echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
-                    echo "RUN_UNITEST_ENABLED=true" >> $GITHUB_ENV
-                    echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
-                    echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
-                    echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
-              else
-                    echo "call by self workflow_dispatch"
-                    echo "RUN_TAG=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
-                    echo "RUN_E2E_LABEL=${{ github.event.inputs.e2e_labels }}" >> $GITHUB_ENV
-                    echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
-                    echo "RUN_UNITEST_ENABLED=true" >> $GITHUB_ENV
-                    if ${{ github.event.inputs.ipfamily == 'ipv4' }}; then
-                      echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
-                      echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
-                      echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
-                    elif ${{ github.event.inputs.ipfamily == 'ipv6' }}; then
-                      echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
-                      echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
-                      echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
-                    elif ${{ github.event.inputs.ipfamily == 'dual' }}; then
-                      echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
-                      echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
-                      echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
-                    elif ${{ github.event.inputs.ipfamily == 'all' }}; then
-                      echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
-                      echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
-                      echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
-                    else
-                      echo "error, unknown input ipfamily: ${{ github.event.inputs.ipfamily }} "
-                      exit 1
-                    fi
-              fi
+                echo "call by self workflow_dispatch"
+                echo "RUN_TAG=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
+                echo "RUN_E2E_LABEL=${{ github.event.inputs.e2e_labels }}" >> $GITHUB_ENV
+                echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
+                echo "RUN_UNITEST_ENABLED=true" >> $GITHUB_ENV
+                if ${{ github.event.inputs.ipfamily == 'ipv4' }}; then
+                  echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
+                  echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
+                  echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
+                elif ${{ github.event.inputs.ipfamily == 'ipv6' }}; then
+                  echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
+                  echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
+                  echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
+                elif ${{ github.event.inputs.ipfamily == 'dual' }}; then
+                  echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
+                  echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
+                  echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
+                elif ${{ github.event.inputs.ipfamily == 'all' }}; then
+                  echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
+                  echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
+                  echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
+                else
+                  echo "error, unknown input ipfamily: ${{ github.event.inputs.ipfamily }} "
+                  exit 1
+                fi
           elif ${{ github.event_name == 'push' }} ; then
               echo "trigger by push"
               echo "RUN_TAG=${{ github.sha }}" >> $GITHUB_ENV
@@ -137,8 +125,16 @@ jobs:
               # do it in another workflow
               echo "RUN_UNITEST_ENABLED=false" >> $GITHUB_ENV
           else
-            echo "uknown event"
-            exit 1
+              # workflow_call event, nightly ci, run all e2e
+              # use main sha for ci image tag
+              echo "trigger by workflow_call"
+              echo "RUN_TAG=main" >> $GITHUB_ENV
+              echo "RUN_E2E_LABEL=" >> $GITHUB_ENV
+              echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
+              echo "RUN_UNITEST_ENABLED=true" >> $GITHUB_ENV
+              echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
+              echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
+              echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
           fi
 
       # some event, the tag is not sha, so checkout it and get sha
@@ -193,6 +189,7 @@ jobs:
   e2e_dual:
     runs-on: ubuntu-latest
     needs: [call_build_ci_image, prepare, call_release_chart]
+    if: ${{ needs.prepare.outputs.e2e_enabled == 'true' && needs.prepare.outputs.ipfamily_dual_e2e == 'true' }}
     uses: ./.github/workflows/call-e2e.yaml
     with:
       ref: ${{ needs.prepare.outputs.ref }}
@@ -229,3 +226,27 @@ jobs:
     with:
       ref: ${{ needs.prepare.outputs.ref }}
     secrets: inherit
+
+  creat_issue:
+    runs-on: ubuntu-latest
+    needs: [ trivy_scan, e2e_ipv6, e2e_ipv4, e2e_dual ]
+    # https://docs.github.com/en/actions/learn-github-actions/contexts#jobs-context
+    if: ${{ always() && ( needs.trivy_scan.result == 'failure' || needs.e2e_ipv6.result == 'failure' || needs.e2e_ipv4.result == 'failure' || needs.e2e_dual.result == 'failure' ) }}
+    steps:
+      - name: echo
+        run: |
+          echo ${{ github.repository }}
+          echo ${{ github.repository_owner }}
+          echo "TIMESTAMP=`date +%Y-%m-%d`" >> $GITHUB_ENV
+
+      - name: create an issue
+        uses: dacbd/create-issue-action@v1.2.1
+        with:
+          token: ${{ secrets.WELAN_PAT }}
+          #owner: spidernet-io
+          #repo: rocktemplae
+          title: "Night CI ${{ ENV.TIMESTAMP }}: Failed"
+          body: |
+            action url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+          labels: "kind/bug"
+          assignees: "weizhoublue"
