23dsa
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/auto-ci.yaml b/.github/workflows/auto-ci.yaml
--- a/.github/workflows/auto-ci.yaml
+++ b/.github/workflows/auto-ci.yaml
@@ -243,7 +243,7 @@ jobs:
         with:
           path: output/artifact
 
-      - name: Load Images
+      - name: Load And Scan Images
         run: |
           cd output/artifact
           ls
@@ -258,6 +258,9 @@ jobs:
               for TAR in $TAR_FILES ; do
                 echo "image tar ${ITEM}/${TAR}"
                 cat ${ITEM}/${TAR} |  docker import - ${TAR%*.tar}:${{ needs.prepare.outputs.ref }}
+                echo "---------trivy checkout image ${TAR%*.tar}:${{ needs.prepare.outputs.ref }} --------------------"
+                make lint_image_trivy -e IMAGE_NAME=${TAR%*.tar}:${{ needs.prepare.outputs.ref }} \
+                    || { echo "RUN_IMAGE_TRIVY_FAIL=true" >> $GITHUB_ENV ; echo "error, image ${TAR%*.tar}:${{ needs.prepare.outputs.ref }} is bad" ; }
               done
           done
           docker images
@@ -487,3 +490,11 @@ jobs:
 #              exit 1
 #          fi
 
+      - name: Show Trivy Scan Report
+        run: |
+          if [ "${{ env.RUN_IMAGE_TRIVY_FAIL }}" == "true" ] ; then
+              echo "error, image is not secure, see detail on Step 'Load And Scan Images' "
+              exit 1
+          else
+              exit 0
+          fi
