flow
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/auto-nightly-ci.yaml b/.github/workflows/auto-nightly-ci.yaml
--- a/.github/workflows/auto-nightly-ci.yaml
+++ b/.github/workflows/auto-nightly-ci.yaml
@@ -1,4 +1,13 @@
+# !!!!!!!!!!!! modify line 4 - 9
+
 name: Auto Nightly CI
+
+ENV:
+  E2E_LOG_PATH: test/runtime/e2edebugLog.txt
+  E2E_GINKGO_REPORT_PATH: test/runtime/ginkgoreport.json
+  PERFORMANCE_SCRIPT: test/scripts/getPerformanceData.sh
+  PERFORMANCE_BADGE_ID:
+  PERFORMANCE_BADGE_FILENAME:
 
 permissions: write-all
 on:
@@ -205,14 +214,11 @@ jobs:
           echo "ipfamily_ipv6only_e2e: ${{ needs.get_ref.outputs.ipfamily_ipv6only_e2e }}"
           echo "ipfamily_dual_e2e: ${{ needs.get_ref.outputs.ipfamily_dual_e2e }}"
           echo "===== image "
-          echo "ci image tag: ghcr.io/${{ github.repository }}/spiderpool-controller-ci:${{ needs.call_build_ci_image.outputs.imageTag }}"
-          echo "ci race image tag: ghcr.io/${{ github.repository }}/spiderpool-controller-ci:${{ needs.call_build_ci_image.outputs.imageTag }}-race"
-          echo "ci image tag: ghcr.io/${{ github.repository }}/spiderpool-agent-ci:${{ needs.call_build_ci_image.outputs.imageTag }}"
-          echo "ci race image tag: ghcr.io/${{ github.repository }}/spiderpool-agent-ci:${{ needs.call_build_ci_image.outputs.imageTag }}-race"
+          echo "ci image tag: ${{ needs.get_ref.outputs.ref }}"
           echo "===== chart "
           echo "chart package artifact: ${{ needs.call_release_chart.outputs.artifact }}"
           TMP=` date +%m%d%H%M%S `
-          E2E_CLUSTER_NAME="spiderpool${TMP}"
+          E2E_CLUSTER_NAME="project{TMP}"
           echo ::set-output name=clusterName::${E2E_CLUSTER_NAME}
 
       - name: Checkout Code
@@ -224,9 +230,253 @@ jobs:
       - name: Setup Golang
         uses: actions/setup-go@v3
         with:
-          go-version: 1.18.2
+          go-version: 1.19.0
           id: go
 
-      - name: Run e2e
+      # https://github.com/helm/kind-action
+      - name: Install Kind Bin
+        uses: helm/kind-action@v1.4.0
+        with:
+          install_only: true
+
+      - name: Download images
+        uses: actions/download-artifact@v3
+        with:
+          name: image-tar-images
+          path: test/.download
+
+      - name: Load Images
         run: |
-          make e2e
+          TAR_FILES=` ls test/.download `
+          echo $TAR_FILES
+          for ITEM in $TAR_FILES ; do
+              IMAGE_NAME=${ITEM%*.tar}
+              cat test/.download/${ITEM} |  docker import - ${IMAGE_NAME}:${{ needs.get_ref.outputs.ref }}
+          done
+
+      # ------------- by default , dual stack
+      # test against commit version
+      - name: Setup Kind Cluster For Dual-stack
+        if: ${{ needs.get_ref.outputs.ipfamily_dual_e2e == 'true' }}
+        uses: nick-invision/retry@v2
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          shell: bash
+          command: |
+            make e2e_init -e KIND_CLUSTER_NAME=${{ steps.prepare.outputs.clusterName }} \
+                -e PROJECT_IMAGE_VERSION=${{ needs.get_ref.outputs.ref }} \
+                -e E2E_IP_FAMILY=dual
+
+      - name: Run e2e Test For Dual-stack
+        id: dualstack_e2e
+        if: ${{ needs.get_ref.outputs.ipfamily_dual_e2e == 'true' }}
+        continue-on-error: true
+        run: |
+          echo ${{ github.event.inputs.labels }}
+          RESULT=0
+          make e2e_test -e KIND_CLUSTER_NAME=${{ steps.prepare.outputs.clusterName }}  \
+              -e E2E_GINKGO_LABELS=${{ needs.get_ref.outputs.e2e_labels }} \
+              -e E2E_IP_FAMILY=dual || RESULT=1
+          if ((RESULT==0)) ; then
+              echo ::set-output name=pass::true
+          else
+              echo ::set-output name=pass::false
+          fi
+          if [ -f "${{ env.E2E_LOG_PATH }}" ] ; then
+              echo ::set-output name=updaloadlog::true
+          else
+              echo ::set-output name=updaloadlog::false
+          fi
+          if [ -f "${{ env.E2E_GINKGO_REPORT_PATH }}" ] ; then
+              echo "error, did not find e2e report"
+              echo ::set-output name=upload::true
+          else
+              echo ::set-output name=upload::false
+          fi
+
+      - name: Upload e2e log For Dual-stack
+        if: ${{ needs.get_ref.outputs.ipfamily_dual_e2e == 'true' }}
+        uses: actions/upload-artifact@v3.1.0
+        with:
+          name: dualstack-debuglog.txt
+          path: ${{ env.E2E_LOG_PATH }}
+          retention-days: 30
+
+      - name: Upload e2e report For Dual-stack
+        if: ${{ steps.dualstack_e2e.outputs.upload == 'true' && needs.get_ref.outputs.ipfamily_dual_e2e == 'true' }}
+        uses: actions/upload-artifact@v3.1.0
+        with:
+          name: dualstack-e2ereport.json
+          path: ${{ env.E2E_GINKGO_REPORT_PATH }}
+          retention-days: 30
+
+      - name: Show e2e Result For Dual-stack
+        if: ${{ needs.get_ref.outputs.ipfamily_dual_e2e == 'true' }}
+        run: |
+          if ${{ steps.dualstack_e2e.outputs.pass == 'true' }} ;then
+              exit 0
+          else
+              exit 1
+          fi
+
+      - name: Get the E2E Performance Result For Dual-stack
+        # run all e2e cases
+        id: get_performance
+        if: ${{ needs.get_ref.outputs.ipfamily_dual_e2e == 'true' }}
+        shell: bash
+        run: |
+          # sudo apt-get install -y jq
+          TOOL_PATH=${{ env.PERFORMANCE_SCRIPT }}
+          TODO_STATUS=$( ${TOOL_PATH}  "${{ env.E2E_GINKGO_REPORT_PATH }}"  )
+          echo ::set-output name=result::${TODO_STATUS}
+
+      - name: Update Badge For Dual-stack
+        if: ${{ steps.get_performance.outputs.result != '' && needs.get_ref.outputs.ipfamily_dual_e2e == 'true' }}
+        uses: schneegans/dynamic-badges-action@v1.5.0
+        with:
+          auth: ${{ secrets.WELAN_PAT }}
+          gistID: ${{ env.PERFORMANCE_BADGE_ID }}
+          filename: ${{ env.PERFORMANCE_BADGE_FILENAME }}
+          label: performance
+          message: ${{ steps.get_performance.outputs.result }}
+          color: lightgrey
+
+#      # ------------------ ipv4-only
+#      # test against commit version
+#      - name: Setup Kind Cluster For ipv4-only
+#        if: ${{ needs.get_ref.outputs.ipfamily_ipv4only_e2e == 'true' }}
+#        uses: nick-invision/retry@v2
+#        with:
+#          timeout_minutes: 10
+#          max_attempts: 3
+#          shell: bash
+#          command: |
+#            make e2e_init -e KIND_CLUSTER_NAME=${{ steps.prepare.outputs.clusterName }} \
+#                -e TEST_IMAGE_TAG=${{ needs.call_build_ci_image.outputs.imageTag }} \
+#                -e SPIDERPOOL_AGENT_IMAGE_NAME=spiderpool-agent-race   \
+#                -e SPIDERPOOL_CONTROLLER_IMAGE_NAME=spiderpool-controller-race \
+#                -e E2E_IP_FAMILY=ipv4
+#
+#      - name: Run e2e Test For ipv4-only
+#        id: ipv4only_e2e
+#        if: ${{ needs.get_ref.outputs.ipfamily_ipv4only_e2e == 'true' }}
+#        continue-on-error: true
+#        run: |
+#          echo ${{ github.event.inputs.labels }}
+#          RESULT=0
+#          make e2e_test -e KIND_CLUSTER_NAME=${{ steps.prepare.outputs.clusterName }}  \
+#              -e E2E_GINKGO_LABELS=${{ needs.get_ref.outputs.e2e_labels }} \
+#              -e E2E_TIMEOUT=${{ env.E2E_TIME_OUT }}  \
+#              -e E2E_IP_FAMILY=ipv4 -e PYROSCOPE_LOCAL_PORT="" || RESULT=1
+#          if ((RESULT==0)) ; then
+#              echo ::set-output name=pass::true
+#          else
+#              echo ::set-output name=pass::false
+#          fi
+#          if [ -f "test/e2edebugLog" ] ; then
+#              echo ::set-output name=updaloadlog::true
+#          else
+#              echo ::set-output name=updaloadlog::false
+#          fi
+#          if [ -f "./e2ereport.json" ] ; then
+#              echo "error, did not find e2e report"
+#              echo ::set-output name=upload::true
+#          else
+#              echo ::set-output name=upload::false
+#          fi
+#
+#      - name: Upload e2e log For ipv4-only
+#        if: ${{ needs.get_ref.outputs.ipfamily_ipv4only_e2e == 'true' }}
+#        uses: actions/upload-artifact@v3.1.0
+#        with:
+#          name: ipv4Only-debuglog.txt
+#          path: test/e2edebugLog.txt
+#          retention-days: 30
+#
+#      - name: Upload e2e report For ipv4-only
+#        if: ${{ steps.ipv4only_e2e.outputs.upload == 'true' && needs.get_ref.outputs.ipfamily_ipv4only_e2e == 'true' }}
+#        uses: actions/upload-artifact@v3.1.0
+#        with:
+#          name: ipv4Only-e2ereport.json
+#          path: e2ereport.json
+#          retention-days: 14
+#
+#      - name: Show e2e Result For ipv4-only
+#        if: ${{ needs.get_ref.outputs.ipfamily_ipv4only_e2e == 'true' }}
+#        run: |
+#          if ${{ steps.ipv4only_e2e.outputs.pass == 'true' }} ;then
+#              exit 0
+#          else
+#              exit 1
+#          fi
+#
+#      # ------------------ ipv6-only
+#      # test against commit version
+#      - name: Setup Kind Cluster For ipv6-only
+#        if: ${{ needs.get_ref.outputs.ipfamily_ipv6only_e2e == 'true' }}
+#        uses: nick-invision/retry@v2
+#        with:
+#          timeout_minutes: 10
+#          max_attempts: 3
+#          shell: bash
+#          command: |
+#            make e2e_init -e KIND_CLUSTER_NAME=${{ steps.prepare.outputs.clusterName }} \
+#                -e TEST_IMAGE_TAG=${{ needs.call_build_ci_image.outputs.imageTag }} \
+#                -e SPIDERPOOL_AGENT_IMAGE_NAME=spiderpool-agent-race   \
+#                -e SPIDERPOOL_CONTROLLER_IMAGE_NAME=spiderpool-controller-race \
+#                -e E2E_IP_FAMILY=ipv6 -e PYROSCOPE_LOCAL_PORT=""
+#
+#      - name: Run e2e Test For ipv6-only
+#        id: ipv6only_e2e
+#        if: ${{ needs.get_ref.outputs.ipfamily_ipv6only_e2e == 'true' }}
+#        continue-on-error: true
+#        run: |
+#          echo ${{ github.event.inputs.labels }}
+#          RESULT=0
+#          make e2e_test -e KIND_CLUSTER_NAME=${{ steps.prepare.outputs.clusterName }}  \
+#              -e E2E_GINKGO_LABELS=${{ needs.get_ref.outputs.e2e_labels }} \
+#              -e E2E_TIMEOUT=${{ env.E2E_TIME_OUT }}  \
+#              -e E2E_IP_FAMILY=ipv6 -e PYROSCOPE_LOCAL_PORT="" || RESULT=1
+#          if ((RESULT==0)) ; then
+#              echo ::set-output name=pass::true
+#          else
+#              echo ::set-output name=pass::false
+#          fi
+#          if [ -f "test/e2edebugLog" ] ; then
+#              echo ::set-output name=updaloadlog::true
+#          else
+#              echo ::set-output name=updaloadlog::false
+#          fi
+#          if [ -f "./e2ereport.json" ] ; then
+#              echo "error, did not find e2e report"
+#              echo ::set-output name=upload::true
+#          else
+#              echo ::set-output name=upload::false
+#          fi
+#
+#      - name: Upload e2e log For ipv6-only
+#        if: ${{ needs.get_ref.outputs.ipfamily_ipv6only_e2e == 'true' }}
+#        uses: actions/upload-artifact@v3.1.0
+#        with:
+#          name: ipv6Only-debuglog.txt
+#          path: test/e2edebugLog.txt
+#          retention-days: 30
+#
+#      - name: Upload e2e report For ipv6-only
+#        if: ${{ steps.ipv6only_e2e.outputs.upload == 'true' && needs.get_ref.outputs.ipfamily_ipv6only_e2e == 'true' }}
+#        uses: actions/upload-artifact@v3.1.0
+#        with:
+#          name: ipv6Only-e2ereport.json
+#          path: e2ereport.json
+#          retention-days: 14
+#
+#      - name: Show e2e Result For ipv6-only
+#        if: ${{ needs.get_ref.outputs.ipfamily_ipv6only_e2e == 'true' }}
+#        run: |
+#          if ${{ steps.ipv6only_e2e.outputs.pass == 'true' }} ;then
+#              exit 0
+#          else
+#              exit 1
+#          fi
+
